name: Release

on:
  workflow_dispatch: 

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  release:
    permissions:
      id-token: write

    runs-on: ubuntu-latest

    if: github.repository == 'priv-kweihmann/systemdlint'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build
      run: |
        python3 setup.py build sdist bdist_wheel --universal

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: dist
